name: social_psn
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <5.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  stylish_bottom_bar: ^1.1.0
  image_picker: ^1.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_localization: ^0.3.1
  graphql_flutter: ^5.2.0-beta.6
  flutter_svg: ^2.0.10+1
  animated_bottom_navigation_bar: ^1.3.3
  pin_code_fields: ^8.0.1
  custom_sliding_segmented_control: ^1.8.1
  flutter_secure_storage: ^9.0.0
  regexpattern: ^2.6.0
  flutter_keyboard_visibility: ^6.0.0
  infinite_scroll_pagination: ^4.0.0
  shamsi_date: ^1.0.2
  intl: ^0.19.0
  persian_number_utility: ^1.1.4
  flutter_launcher_icons: ^0.14.1
  flutter_advanced_switch: ^3.1.0
  http: ^1.2.1
  crypto: ^3.0.3
  mime: ^2.0.0
  flutter_native_splash: ^2.4.0
  clipboard: ^0.1.3
  image_cropper: ^8.0.2
  font_awesome_flutter: '>= 4.7.0'
  carousel_slider: ^5.0.0
  flick_video_player: ^0.9.0
  video_player: ^2.8.7
  dots_indicator: ^3.0.0
  visibility_detector: ^0.4.0+2
  inview_notifier_list: ^3.0.0
  equatable: ^2.0.5
  dotted_border: ^2.1.0
  badges: ^3.1.2
  chewie: ^1.8.1
  modal_bottom_sheet: ^3.0.0
  reorderables: ^0.6.0
  dio: ^5.5.0+1
  firebase_core: ^3.8.0
  firebase_messaging: ^15.0.4
  flutter_typeahead: ^5.2.0
  permission_handler: ^11.3.1
  file_picker: ^8.0.7
  just_audio: ^0.9.40
  flutter_local_notifications: ^18.0.1
  video_thumbnail: ^0.5.3
  gql_dio_link: ^1.0.1+1
  share_plus: ^10.1.2
  double_back_to_close_app: ^2.1.0
  double_tap_to_exit: ^1.0.1
  back_button_interceptor: ^8.0.0
  extended_nested_scroll_view: ^6.2.1
  pull_to_refresh_notification: ^3.1.0
  dropdown_textfield: ^1.2.0
  emoji_picker_flutter: ^4.2.0
  searchfield: ^1.2.2
  auto_scroll_text: ^0.0.7
  url_launcher: ^6.3.1
  maps_launcher: ^3.0.0+1
  android_intent_plus: ^5.3.0
  dropdown_button2: ^2.3.9
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  font_awesome_flutter:
    path: 'assets\font_awesome\font_awesome_flutter'

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash/logo.png"
  min_sdk_android: 21
  cupertino_icons: ^1.0.5
  remove_alpha_ios: true
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.



  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the images in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/configs/localization/
    - assets/images/appbar/
    - assets/images/bottom_navbar/
    - assets/images/profile/
    - assets/images/drawer/
    - assets/images/notification/
    - assets/images/post/
    - assets/images/search/
    - assets/images/consult/

  fonts:
    - family: IRANSansX
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-Black.ttf
        - asset: assets/fonts/IRANSansXFaNum-Bold.ttf
          weight: 700
        - asset: assets/fonts/IRANSansXFaNum-DemiBold.ttf
        - asset: assets/fonts/IRANSansXFaNum-ExtraBold.ttf
        - asset: assets/fonts/IRANSansXFaNum-ExtraBlack.ttf
        - asset: assets/fonts/IRANSansXFaNum-Heavy.ttf
        - asset: assets/fonts/IRANSansXFaNum-Light.ttf
        - asset: assets/fonts/IRANSansXFaNum-Medium.ttf
        - asset: assets/fonts/IRANSansXFaNum-Regular.ttf
        - asset: assets/fonts/IRANSansXFaNum-Thin.ttf
        - asset: assets/fonts/IRANSansXFaNum-Ultralight.ttf

    - family: Iranyekan
      fonts:
        - asset: assets/fonts/Iranyekan-Regular.ttf
        - asset: assets/fonts/Iranyekan-Bold.ttf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
